"""empty message

Revision ID: 34f9cfc8004f
Revises: d509598131ee
Create Date: 2018-04-27 10:56:06.018861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '34f9cfc8004f'
down_revision = 'd509598131ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boats_user_id_fkey', 'boats', type_='foreignkey')
    op.create_foreign_key(None, 'boats', 'users', ['user_id'], ['id'])
    op.add_column('dives', sa.Column('times', sa.ARRAY(sa.Time(), dimensions=2), nullable=True))
    op.drop_column('dives', 'startTime')
    op.drop_column('dives', 'endTime')
    op.drop_index('idx_divesites_geom', table_name='divesites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_divesites_geom', 'divesites', ['geom'], unique=False)
    op.add_column('dives', sa.Column('endTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('dives', sa.Column('startTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('dives', 'times')
    op.drop_constraint(None, 'boats', type_='foreignkey')
    op.create_foreign_key('boats_user_id_fkey', 'boats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
