"""empty message

Revision ID: 90712661b739
Revises: 
Create Date: 2018-05-16 14:20:16.472470

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '90712661b739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divesites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenced', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typedives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weathers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sky', sa.String(length=255), nullable=True),
    sa.Column('sea', sa.String(length=255), nullable=True),
    sa.Column('wind', sa.String(length=255), nullable=True),
    sa.Column('water_temperature', sa.Integer(), nullable=True),
    sa.Column('wind_temperature', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('matriculation', sa.Unicode(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriculation')
    )
    op.create_table('dives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('times', sa.ARRAY(sa.Time(), dimensions=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['divesites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weather_id'], ['weathers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('status', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['divesites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diveboats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('boat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divetypedives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('divetype_id', sa.Integer(), nullable=True),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('divers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['divetype_id'], ['typedives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divetypedives')
    op.drop_table('diveboats')
    op.drop_table('permits')
    op.drop_table('dives')
    op.drop_table('boats')
    op.drop_table('weathers')
    op.drop_table('users')
    op.drop_table('typedives')
    op.drop_table('divesites')
    # ### end Alembic commands ###
