"""empty message

Revision ID: c71ecffcfd81
Revises: 
Create Date: 2018-05-11 15:01:30.417896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71ecffcfd81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('address_standardizer_data_us')
    #op.drop_table('us_gaz')
    #op.drop_table('us_lex')
    op.add_column('dives', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('dives', sa.Column('longitude', sa.String(), nullable=True))
    op.drop_index('idx_divesites_geom', table_name='divesites')
    op.drop_constraint('divetypedives_divetype_id_fkey', 'divetypedives', type_='foreignkey')
    op.create_foreign_key(None, 'divetypedives', 'typedives', ['divetype_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'website')
    op.drop_constraint(None, 'divetypedives', type_='foreignkey')
    op.create_foreign_key('divetypedives_divetype_id_fkey', 'divetypedives', 'divesites', ['divetype_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_divesites_geom', 'divesites', ['geom'], unique=False)
    op.drop_column('dives', 'longitude')
    op.drop_column('dives', 'latitude')
    op.create_table('us_lex',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_lex')
    )
    op.create_table('us_gaz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_gaz')
    )
    op.create_table('us_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_rules')
    )
    # ### end Alembic commands ###
