"""empty message

Revision ID: d46cca4bc063
Revises: f65577e4b0cc
Create Date: 2018-04-25 22:51:19.250019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46cca4bc063'
down_revision = 'f65577e4b0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('typedives', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('weathers', sa.Column('seaState', sa.String(length=255), nullable=True))
    op.add_column('weathers', sa.Column('sky', sa.String(length=255), nullable=True))
    op.add_column('weathers', sa.Column('wind', sa.String(length=255), nullable=True))
    op.drop_column('weathers', 'sky_id')
    op.drop_column('weathers', 'seaState_id')
    op.drop_column('weathers', 'wind_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('wind_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weathers', sa.Column('seaState_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weathers', sa.Column('sky_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('weathers', 'wind')
    op.drop_column('weathers', 'sky')
    op.drop_column('weathers', 'seaState')
    op.alter_column('typedives', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
