"""empty message

Revision ID: d509598131ee
Revises: 
Create Date: 2018-04-27 09:33:12.041958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd509598131ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divesites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenced', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typedives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weathers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sky', sa.String(length=255), nullable=True),
    sa.Column('seaState', sa.String(length=255), nullable=True),
    sa.Column('wind', sa.String(length=255), nullable=True),
    sa.Column('water_temperature', sa.Integer(), nullable=True),
    sa.Column('wind_temperature', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('matriculation', sa.Unicode(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriculation')
    )
    op.create_table('dives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('divingDate', sa.DateTime(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('divesite_id', sa.Integer(), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['divesite_id'], ['divesites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weather_id'], ['weathers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('validity', sa.Unicode(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('endAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('divesite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['divesite_id'], ['divesites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diveboats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('boat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divetypedives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('divetype_id', sa.Integer(), nullable=True),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('nbrDivers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['divetype_id'], ['divesites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('boats', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('divetypedives')
    op.drop_table('diveboats')
    op.drop_table('permits')
    op.drop_table('dives')
    op.drop_table('boats')
    op.drop_table('weathers')
    op.drop_table('users')
    op.drop_table('typedives')
    op.drop_table('divesites')
    # ### end Alembic commands ###
