"""empty message

Revision ID: f95bc6125485
Revises: 34f9cfc8004f
Create Date: 2018-05-10 13:35:48.577397

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f95bc6125485'
down_revision = '34f9cfc8004f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('divetypedives_divetype_id_fkey', 'divetypedives', type_='foreignkey')
    op.create_foreign_key(None, 'divetypedives', 'typedives', ['divetype_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'divetypedives', type_='foreignkey')
    op.create_foreign_key('divetypedives_divetype_id_fkey', 'divetypedives', 'divesites', ['divetype_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
